with-expecter: true
filename: "{{.InterfaceName | snakecase}}_mock.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}Mock"
outpkg: "mocks"
packages:
  github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/interfaces:
    interfaces:
      EthClient:
