name: Generate Tag Name
description: "Generates a tag name based on branch"
runs:
  using: "composite"
  steps:
    - name: Determine tag name
      id: tag
      shell: bash
      run: |
        VMAJ=1
        VMIN=0
        VPAT=0
        set +o pipefail
        VLAST=$(git describe --tags --abbrev=0 --match='v[1-9]*' refs/remotes/origin/main 2>/dev/null | cut -c2-)
        [ $VLAST ] && declare $(echo $VLAST | awk -F '.' '{print "VMAJ="$1" VMIN="$2" VPAT="$3}')
        if [ "$GITHUB_REF_NAME" = "main" ]
        then
            VPAT=0
            VMIN=$((VMIN+1))
            VFULL=${VMAJ}.${VMIN}.${VPAT}
            VTAG=v$VFULL
        else
            MB=$(git merge-base refs/remotes/origin/main HEAD)
            VPAT=$(git rev-list --count --no-merges ${MB}..HEAD)
            VFULL=${VMAJ}.${VMIN}.${VPAT}
            RNAME=${GITHUB_REF_NAME##*/}
            [ "$GITHUB_EVENT_NAME" = "pull_request" ] && RNAME=pr${GITHUB_REF_NAME%/merge}
            VTAG=v${VFULL}-${RNAME}
        fi
        echo "VLAST=$VLAST VMAJ=$VMAJ VMIN=$VMIN VPAT=$VPAT VFULL=$VFULL VTAG=$VTAG"
        echo "TAG_NAME=${VTAG}" >> $GITHUB_ENV
        echo "VTAG=${VTAG}" >> $GITHUB_ENV
        echo "VFULL=${VFULL}" >> $GITHUB_ENV
